name: Disable Checking ServerName

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        DOCKER_FILE: ['Dockerfile', 'Dockerfile.alpine']
        include:
            - DOCKER_FILE: 'Dockerfile'
              DOCKER_TAG: 'latest'
            - DOCKER_FILE: 'Dockerfile.alpine'
              DOCKER_TAG: 'alpine'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: modify
        run: |
          cd tailscale
          sed -i '/hi.ServerName != m.hostname/,+2d' cmd/derper/cert.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Runs a single command using the runners shell
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          file: ${{ matrix.DOCKER_FILE }}
          platforms: linux/arm64, linux/amd64
          context: ./
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ip_derper:${{ matrix.DOCKER_TAG }}

